data_1 = {
    "Title": "Referral Order",
    "Date": "05/10/2024",
    "To Provider": "Cardiology Partners",
    "Phone": "(555) 789-1234",
    "Fax": "(555) 789-5678",
    "Name": "Dr. Robert Patel",
    "Practice": "Community Health Center",
    "Address": "321 Pine Road, Suite 200, Anytown, USA 12345",
    "Phone": "(555) 789-1234",
    "Fax": "(555) 789-5678",
    "Diagnosis": "Syncope and collapse",
    "ICD-10": "R55: Syncope and collapse",
    "Order Name": "Orders included: 1, Cardiology Consultation, CARDIOLOGY REFERRAL",
    "Schedule Within": "1 week",
    "Note to Provider": "Please evaluate for potential cardiac causes of syncope and provide recommendations for further testing and management.",
    "Reason for Referral": "Recurrent syncope",
    "of requested visits": "1",
    "Patient Name": "Elizabeth Davis",
    "Sex": "F",
    "DOB": "09/08/1972",
    "Age": "51y8mo",
    "Patient Address": "789 Maple Avenue, Anytown, USA 12345",
    "Patient Phone": "H: (555) 246-8013, M: (555) 135-7902",
    "Primary Insurance": "Aetna (PPO)",
    "ID": "123456789012",
    "Policy Holder": "Elizabeth Davis",
    "Secondary Insurance": "None recorded.",
    "Notes": "Patient has experienced three episodes of syncope over the past six months. The most recent episode occurred two weeks ago, resulting in a fall and minor head trauma. Patient reports feeling lightheaded and dizzy prior to losing consciousness, with no prodromal symptoms. Episodes are not associated with chest pain, palpitations, or shortness of breath. Patient has a history of hypertension, treated with hydrochlorothiazide 25mg daily, and hyperlipidemia, treated with atorvastatin 20mg daily. No family history of sudden cardiac death or arrhythmias. Physical examination reveals a blood pressure of 135/85 mmHg, heart rate of 68 bpm, and no murmurs or neurological deficits. ECG shows sinus rhythm with no significant abnormalities. Please evaluate and provide recommendations for further testing and management.",
    "Signature": "Electronically Signed by: Dr. Robert Patel",
    "Footer": "COMMUNITY HEALTH CENTER • 321 PINE ROAD, SUITE 200, ANYTOWN, USA 12345, DAVIS, Elizabeth (id #345678, dob: 09/08/1972)"
}

data_2 = {
    "Title": "Referral Order",
    "Date": "04/02/2024",
    "To Provider": "Heartcare Cardiology Group",
    "Phone": "(555) 555-1234",  # This captures the provider's phone
    "Fax": "(555) 555-5678",  # This captures the provider's fax
    "Name": "Dr. Emily Chen",
    "Practice": "Downtown Family Medicine",
    "Address": "789 Elm Avenue, Suite 100, Anytown, USA 12345",  # This captures the from provider's address
    "Diagnosis": "Palpitations",
    "ICD-10": "R00.2: Palpitations",
    "Order Name": "Orders included: 1, Cardiology Evaluation, CARDIOLOGY REFERRAL",
    "Schedule Within": "1 week",
    "Note to Provider": "Please evaluate for potential arrhythmia and provide recommendations for further testing and management.",
    "Reason for Referral": "Palpitations and lightheadedness",
    "of requested visits": "1",
    "Patient Name": "Michael Johnson",
    "Sex": "M",
    "DOB": "05/22/1985",
    "Age": "38y10mo",
    "Patient Address": "456 Oak Street, Anytown, USA 12345",
    "Patient Phone": "H: (555) 987-6543, M: (555) 123-4567",
    "Primary Insurance": "United Healthcare (HMO)",
    "ID": "XYZ987654321",
    "Policy Holder": "Michael Johnson",
    "Secondary Insurance": "None recorded.",
    "Notes": "Patient has been experiencing intermittent palpitations and lightheadedness for the past month. Palpitations are described as a rapid, fluttering sensation in the chest, lasting for several minutes at a time. Lightheadedness occurs concurrently with the palpitations and resolves spontaneously. Patient denies chest pain, shortness of breath, or syncope. No significant past medical history. Family history is notable for atrial fibrillation in his mother, diagnosed at age 60. Patient is a non-smoker and drinks alcohol socially. Physical examination reveals a blood pressure of 130/80 mmHg, heart rate of 72 bpm, and no murmurs or extra heart sounds. ECG shows sinus rhythm with occasional premature atrial contractions. Please evaluate and provide recommendations for further testing and management.",
    "Signature": "Electronically Signed by: Dr. Emily Chen",
    "Footer": "DOWNTOWN FAMILY MEDICINE • 789 ELM AVENUE, SUITE 100, ANYTOWN, USA 12345, JOHNSON, Michael (id #789012, dob: 05/22/1985)"
}